# Generated by Django 6.0.1 on 2026-01-13 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
        ("leagues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Championship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Championship name (e.g., '2025 Season 1', 'Winter Cup')",
                        max_length=200,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        help_text="Season identifier (e.g., '2025', 'Winter 2025')",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "participant_type",
                    models.CharField(
                        choices=[("TEAM", "Team"), ("INDIVIDUAL", "Individual")],
                        default="INDIVIDUAL",
                        max_length=20,
                    ),
                ),
                (
                    "min_drivers_per_team",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                (
                    "max_drivers_per_team",
                    models.IntegerField(blank=True, default=3, null=True),
                ),
                (
                    "point_system",
                    models.JSONField(
                        default=dict,
                        help_text="Point system as JSON (e.g., {'1': 25, '2': 18, '3': 15, ...})",
                    ),
                ),
                (
                    "allowed_car_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Allowed car categories as JSON array (e.g., ['HYPERCAR', 'LMP2'])",
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of participants (teams or drivers)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UPCOMING",
                        help_text="Current championship status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="championships",
                        to="leagues.league",
                    ),
                ),
            ],
            options={
                "verbose_name": "Championship",
                "verbose_name_plural": "Championships",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("racing_number", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cars.car"
                    ),
                ),
                (
                    "championship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="championships.championship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "ordering": ["racing_number"],
                "unique_together": {
                    ("championship", "name"),
                    ("championship", "racing_number"),
                },
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "racing_number",
                    models.IntegerField(help_text="Driver or team racing number"),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Driver role in team (e.g., 'Pro', 'Am', 'Silver', 'Gold'). Only for team championships.",
                        max_length=100,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        help_text="Car used by this driver/team",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cars.car",
                    ),
                ),
                (
                    "championship",
                    models.ForeignKey(
                        help_text="Championship this participant is registered in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="championships.championship",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team this driver belongs to (only for team championships)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="championships.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "ordering": ["racing_number"],
                "unique_together": {
                    ("championship", "driver"),
                    ("championship", "racing_number"),
                },
            },
        ),
    ]
