# Generated by Django 6.0.1 on 2026-01-14 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
        ("championships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "racing_number",
                    models.IntegerField(help_text="Driver or team racing number"),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Driver role in team (e.g., 'Pro', 'Am', 'Silver', 'Gold'). Only for team championships.",
                        max_length=100,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        help_text="Car used by this driver/team",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cars.car",
                    ),
                ),
                (
                    "championship",
                    models.ForeignKey(
                        help_text="Championship this participant is registered in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="championships.championship",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team this driver belongs to (only for team championships)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="championships.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "ordering": ["racing_number"],
                "unique_together": {
                    ("championship", "racing_number"),
                    ("championship", "user"),
                },
            },
        ),
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
