# Generated by Django 6.0.1 on 2026-01-14 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championships", "0002_driver_delete_participant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0, help_text="Current position in championship"
                    ),
                ),
                (
                    "total_points",
                    models.IntegerField(
                        default=0, help_text="Total championship points"
                    ),
                ),
                (
                    "races_completed",
                    models.IntegerField(
                        default=0, help_text="Number of races completed"
                    ),
                ),
                (
                    "wins",
                    models.IntegerField(
                        default=0, help_text="Number of race wins (P1)"
                    ),
                ),
                (
                    "podiums",
                    models.IntegerField(
                        default=0, help_text="Number of podium finishes (P1-P3)"
                    ),
                ),
                (
                    "fastest_laps",
                    models.IntegerField(default=0, help_text="Number of fastest laps"),
                ),
                (
                    "dnf_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of DNFs (Did Not Finish)",
                        verbose_name="DNF count",
                    ),
                ),
                (
                    "dsq_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of disqualifications",
                        verbose_name="DSQ count",
                    ),
                ),
                (
                    "best_finish",
                    models.IntegerField(
                        blank=True,
                        help_text="Best finishing position in this championship",
                        null=True,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "championship",
                    models.ForeignKey(
                        help_text="Championship this standing belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="championships.championship",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Driver (only for INDIVIDUAL championships)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="championships.driver",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team (only for TEAM championships)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="championships.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standing",
                "verbose_name_plural": "Standings",
                "ordering": ["championship", "-total_points"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("driver__isnull", False)),
                        fields=("championship", "driver"),
                        name="unique_driver_standing_per_championship",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("team__isnull", False)),
                        fields=("championship", "team"),
                        name="unique_team_standing_per_championship",
                    ),
                ],
            },
        ),
    ]
