# Generated by Django 6.0.1 on 2026-01-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="publisher",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
