# Generated by Django 6.0.1 on 2026-01-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("short_name", models.CharField(max_length=20, unique=True)),
                ("developer", models.CharField(blank=True, max_length=100)),
                ("publisher", models.CharField(blank=True, max_length=100)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("website", models.URLField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Game is currently supported"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HYPERCAR", "Hypercar"),
                            ("LMGT3", "LMGT3"),
                            ("LPM2", "LPM2"),
                            ("LPM3", "LPM3"),
                            ("GTE", "GTE"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
            ],
            options={
                "verbose_name": "Car Subcategory",
                "verbose_name_plural": "Car Subcategories",
                "ordering": ["category", "name"],
                "unique_together": {("category", "code")},
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("manufacturer", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HYPERCAR", "Hypercar"),
                            ("LMGT3", "LMGT3"),
                            ("LPM2", "LPM2"),
                            ("LPM3", "LPM3"),
                            ("GTE", "GTE"),
                        ],
                        max_length=30,
                    ),
                ),
                ("year", models.IntegerField()),
                ("engine", models.CharField(blank=True, max_length=200)),
                (
                    "power_hp",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Power (HP)"
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Weight (Kg)"
                    ),
                ),
                (
                    "length",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Length (mm)"
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Width (mm)"
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Height (mm)"
                    ),
                ),
                ("transmission", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_dlc", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cars",
                        to="core.carsubcategory",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game where this car is available",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="core.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
                "ordering": [
                    "-created_at",
                    "-updated_at",
                    "name",
                    "manufacturer",
                    "category",
                    "subcategory",
                    "year",
                ],
            },
        ),
    ]
