# Generated by Django 6.0.1 on 2026-03-09 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Championship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Championship name (e.g., '2025 Season 1', 'Winter Cup')",
                        max_length=200,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        help_text="Season identifier (e.g., '2025', 'Winter 2025')",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "participant_type",
                    models.CharField(
                        choices=[("TEAM", "Team"), ("INDIVIDUAL", "Individual")],
                        default="INDIVIDUAL",
                        max_length=20,
                    ),
                ),
                (
                    "min_drivers_per_team",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                (
                    "max_drivers_per_team",
                    models.IntegerField(blank=True, default=3, null=True),
                ),
                (
                    "point_system",
                    models.JSONField(
                        default=dict,
                        help_text="Point system as JSON (e.g., {'1': 25, '2': 18, '3': 15, ...})",
                    ),
                ),
                (
                    "allowed_car_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Allowed car categories as JSON array (e.g., ['HYPERCAR', 'LMP2'])",
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of participants (teams or drivers)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UPCOMING",
                        help_text="Current championship status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Championship",
                "verbose_name_plural": "Championships",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("short_name", models.CharField(max_length=20, unique=True)),
                ("developer", models.CharField(blank=True, max_length=100)),
                ("publisher", models.CharField(blank=True, max_length=100)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("website", models.URLField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Game is currently supported"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="team_logo/"),
                ),
                ("description", models.TextField(blank=True)),
                ("total_races", models.PositiveIntegerField(default=0)),
                ("total_wins", models.PositiveIntegerField(default=0)),
                ("total_podiums", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CarSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HYPERCAR", "Hypercar"),
                            ("LMGT3", "LMGT3"),
                            ("LPM2", "LPM2"),
                            ("LPM3", "LPM3"),
                            ("GTE", "GTE"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
            ],
            options={
                "verbose_name": "Car Subcategory",
                "verbose_name_plural": "Car Subcategories",
                "ordering": ("category", "name"),
                "unique_together": {("category", "code")},
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("manufacturer", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HYPERCAR", "Hypercar"),
                            ("LMGT3", "LMGT3"),
                            ("LPM2", "LPM2"),
                            ("LPM3", "LPM3"),
                            ("GTE", "GTE"),
                        ],
                        max_length=30,
                    ),
                ),
                ("year", models.IntegerField()),
                ("engine", models.CharField(blank=True, max_length=200)),
                (
                    "power_hp",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Power (HP)"
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Weight (Kg)"
                    ),
                ),
                (
                    "length",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Length (mm)"
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Width (mm)"
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Height (mm)"
                    ),
                ),
                ("transmission", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_dlc", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cars",
                        to="core.carsubcategory",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game where this car is available",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="core.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
                "ordering": [
                    "-created_at",
                    "-updated_at",
                    "name",
                    "manufacturer",
                    "category",
                    "subcategory",
                    "year",
                ],
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "racing_number",
                    models.IntegerField(help_text="Driver or team racing number"),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Driver role in team (e.g., 'Pro', 'Am', 'Silver', 'Gold'). Only for team championship.",
                        max_length=100,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        help_text="Car used by this driver/team",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.car",
                    ),
                ),
                (
                    "championship",
                    models.ForeignKey(
                        help_text="Championship this participant is registered in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="core.championship",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team this driver belongs to (only for team championship)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
                "ordering": ["racing_number"],
                "unique_together": {
                    ("championship", "racing_number"),
                    ("championship", "user"),
                },
            },
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="League name (e.g., 'Friday Night Endurance League')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="League description and rules"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public (Anyone can join)"),
                            ("INVITE_ONLY", "Invite Only (Need invitation code)"),
                            ("PRIVATE", "Private (Admin approval required)"),
                        ],
                        default="PUBLIC",
                        help_text="League visibility and join requirements",
                        max_length=20,
                    ),
                ),
                (
                    "invitation_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique invitation code for INVITE_ONLY leagues",
                        max_length=32,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leagues",
                        to="core.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "League",
                "verbose_name_plural": "Leagues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="championship",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="championships",
                to="core.league",
            ),
        ),
        migrations.CreateModel(
            name="LeagueMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("MODERATOR", "Moderator"),
                            ("MEMBER", "Member"),
                        ],
                        default="MEMBER",
                        help_text="Member role in the league",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.league",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "League Membership",
                "verbose_name_plural": "League Memberships",
                "ordering": ["-joined_at"],
                "unique_together": {("league", "user")},
            },
        ),
        migrations.AddField(
            model_name="league",
            name="members",
            field=models.ManyToManyField(
                related_name="leagues",
                through="core.LeagueMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "layout",
                    models.CharField(
                        blank=True,
                        help_text="Track layout (e.g. Full Circuit, Short, GP)",
                        max_length=100,
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("corners", models.IntegerField(help_text="Number of corners")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Track description and history"
                    ),
                ),
                ("is_dlc", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="core.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Track",
                "verbose_name_plural": "Tracks",
                "ordering": ["game", "name", "layout", "length", "corners"],
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "round_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Race round number (only for championship races)",
                        null=True,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        help_text="Scheduled date and time of the race"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Race duration in minutes (e.g., 360 for 6 hours)",
                        null=True,
                    ),
                ),
                (
                    "laps",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of laps (if race is by laps instead of time)",
                        null=True,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public (Anyone can view)"),
                            ("UNLISTED", "Unlisted (Only with link)"),
                            ("PRIVATE", "Private (League members only)"),
                        ],
                        default="PUBLIC",
                        help_text="Race visibility level",
                        max_length=20,
                    ),
                ),
                (
                    "invitation_code",
                    models.CharField(
                        blank=True,
                        help_text="Invitation code for UNLISTED races",
                        max_length=32,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "entered_at",
                    models.DateTimeField(
                        blank=True, help_text="When results were entered", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the race (incidents, weather, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "championship",
                    models.ForeignKey(
                        blank=True,
                        help_text="Championship this race belongs to (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to="core.championship",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Race creator",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_races",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who entered the results",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_races",
                        to="core.driver",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        blank=True,
                        help_text="League this race belongs to (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to="core.league",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        help_text="Track where this race takes place",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Race",
                "verbose_name_plural": "Races",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="LeagueJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="Status of the join request",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional message from the user"
                    ),
                ),
                (
                    "admin_message",
                    models.TextField(
                        blank=True, help_text="Optional message from admin"
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="core.league",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "League Join Request",
                "verbose_name_plural": "League Join Requests",
                "ordering": ["-requested_at"],
                "unique_together": {("league", "user", "status")},
            },
        ),
        migrations.CreateModel(
            name="Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0, help_text="Current position in championship"
                    ),
                ),
                (
                    "total_points",
                    models.IntegerField(
                        default=0, help_text="Total championship points"
                    ),
                ),
                (
                    "races_completed",
                    models.IntegerField(
                        default=0, help_text="Number of races completed"
                    ),
                ),
                (
                    "wins",
                    models.IntegerField(
                        default=0, help_text="Number of race wins (P1)"
                    ),
                ),
                (
                    "podiums",
                    models.IntegerField(
                        default=0, help_text="Number of podium finishes (P1-P3)"
                    ),
                ),
                (
                    "fastest_laps",
                    models.IntegerField(default=0, help_text="Number of fastest laps"),
                ),
                (
                    "dnf_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of DNFs (Did Not Finish)",
                        verbose_name="DNF count",
                    ),
                ),
                (
                    "dsq_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of disqualifications",
                        verbose_name="DSQ count",
                    ),
                ),
                (
                    "best_finish",
                    models.IntegerField(
                        blank=True,
                        help_text="Best finishing position in this championship",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "championship",
                    models.ForeignKey(
                        help_text="Championship this standing belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="core.championship",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Driver (only for INDIVIDUAL championship)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="core.driver",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team (only for TEAM championship)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standing",
                "verbose_name_plural": "Standings",
                "ordering": ["championship", "-total_points"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("driver__isnull", False)),
                        fields=("championship", "driver"),
                        name="unique_driver_standing_per_championship",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("team__isnull", False)),
                        fields=("championship", "team"),
                        name="unique_team_standing_per_championship",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "total_time",
                    models.DurationField(
                        blank=True,
                        help_text="Total race time (for time-based races)",
                        null=True,
                    ),
                ),
                (
                    "laps_completed",
                    models.IntegerField(
                        blank=True, help_text="Number of laps completed", null=True
                    ),
                ),
                (
                    "fastest_lap_time",
                    models.DurationField(
                        blank=True,
                        help_text="Fastest lap time during the race",
                        null=True,
                    ),
                ),
                ("fastest_lap", models.BooleanField(default=False)),
                ("dnf", models.BooleanField(default=False, verbose_name="DNF")),
                ("dsq", models.BooleanField(default=False, verbose_name="DSQ")),
                (
                    "points",
                    models.IntegerField(
                        default=0,
                        help_text="Championship points earned (only for championship races)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes (incidents, penalties, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        help_text="Driver who achieved this result",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_results",
                        to="core.driver",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        help_text="Race this result belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.race",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team this result belongs to (only for TEAM championship)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_race_results",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Race Result",
                "verbose_name_plural": "Race Results",
                "ordering": ["race", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("race", "position"), name="unique_position_per_race"
                    ),
                    models.UniqueConstraint(
                        fields=("race", "driver"), name="unique_driver_per_race"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("team__isnull", False)),
                        fields=("race", "team"),
                        name="unique_team_per_race",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeagueTeamRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("BANNED", "Banned"),
                        ],
                        default="PENDING",
                        help_text="Team registration status",
                        max_length=20,
                    ),
                ),
                (
                    "ban_reason",
                    models.TextField(
                        blank=True, help_text="Banned reason (if status is banned"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        help_text="League team registration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_registrations",
                        to="core.league",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_team_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team registration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_registrations",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "LeagueTeamRegistration",
                "verbose_name_plural": "LeagueTeamRegistrations",
                "ordering": ("created_at",),
                "unique_together": {("league", "team")},
            },
        ),
        migrations.CreateModel(
            name="TeamJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from the user explaining why they want to join",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owner/manager who accepted or rejected the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_team_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team join request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="core.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User join request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TeamJoinRequest",
                "verbose_name_plural": "TeamJoinRequests",
                "ordering": ("team", "created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("team", "user"),
                        name="unique_team_join_request_pending",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("DRIVER", "Driver"),
                            ("RESERVE", "Reserve"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team this membership belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who is a member of this team",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TeamMembership",
                "verbose_name_plural": "TeamMemberships",
                "ordering": ("team", "created_at"),
                "unique_together": {("team", "user")},
            },
        ),
        migrations.AddConstraint(
            model_name="race",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("championship__isnull", False), ("round_number__isnull", False)
                ),
                fields=("championship", "round_number"),
                name="unique_round_per_championship",
            ),
        ),
    ]
