# Generated by Django 6.0.1 on 2026-01-30 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carsubcategory",
            options={
                "ordering": ("category", "name"),
                "verbose_name": "Car Subcategory",
                "verbose_name_plural": "Car Subcategories",
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ("name",),
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="team",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="team_logo/"),
        ),
        migrations.AddField(
            model_name="team",
            name="total_podiums",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="total_races",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="total_wins",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name="team",
            name="car",
        ),
        migrations.RemoveField(
            model_name="team",
            name="championship",
        ),
        migrations.RemoveField(
            model_name="team",
            name="racing_number",
        ),
        migrations.CreateModel(
            name="LeagueTeamRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("BANNED", "Banned"),
                        ],
                        default="PENDING",
                        help_text="Team registration status",
                        max_length=20,
                    ),
                ),
                (
                    "ban_reason",
                    models.TextField(
                        blank=True, help_text="Banned reason (if status is banned"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        help_text="League team registration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_registrations",
                        to="core.league",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_team_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team registration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_registrations",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "LeagueTeamRegistration",
                "verbose_name_plural": "LeagueTeamRegistrations",
                "ordering": ("created_at",),
                "unique_together": {("league", "team")},
            },
        ),
        migrations.CreateModel(
            name="TeamJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from the user explaining why they want to join",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owner/manager who accepted or rejected the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_team_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team join request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="core.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User join request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TeamJoinRequest",
                "verbose_name_plural": "TeamJoinRequests",
                "ordering": ("team", "created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("team", "user"),
                        name="unique_team_join_request_pending",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("DRIVER", "Driver"),
                            ("RESERVE", "Reserve"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team this membership belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who is a member of this team",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TeamMembership",
                "verbose_name_plural": "TeamMemberships",
                "ordering": ("team", "created_at"),
                "unique_together": {("team", "user")},
            },
        ),
    ]
