# Generated by Django 6.0.1 on 2026-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
