# Generated by Django 6.0.1 on 2026-01-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaguemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MODERATOR", "Moderator"),
                    ("MEMBER", "Member"),
                ],
                default="MEMBER",
                help_text="Member role in the league",
                max_length=10,
            ),
        ),
    ]
