# Generated by Django 6.0.1 on 2026-05-13 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_race_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="racelineup",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="racelineup",
            name="role",
        ),
        migrations.RemoveField(
            model_name="racelineup",
            name="user",
        ),
        migrations.CreateModel(
            name="RaceLineupDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Driver category/role (e.g. Pro, Am, Silver, Gold)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lineup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineup_drivers",
                        to="core.racelineup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_lineup_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RaceLineupDriver",
                "verbose_name_plural": "RaceLineupDrivers",
                "unique_together": {("lineup", "user")},
            },
        ),
    ]
