# Generated by Django 6.0.1 on 2026-05-21 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_racelineup_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_usage",
                    models.CharField(
                        choices=[
                            ("OFF", "Off"),
                            ("X1", "x1"),
                            ("X2", "x2"),
                            ("X3", "x3"),
                            ("X5", "x5"),
                        ],
                        default="X1",
                        help_text="LMU-specific values. Will move to Game.fuel_usage_options for multi-sim support.",
                        max_length=10,
                    ),
                ),
                (
                    "tire_wear",
                    models.CharField(
                        choices=[("X1", "x1"), ("X2", "x2"), ("X3", "x3")],
                        default="X1",
                        help_text="LMU-specific values. Will move to Game.tire_wear_options for multi-sim support.",
                        max_length=10,
                    ),
                ),
                ("tire_warmers", models.BooleanField(default=True)),
                (
                    "mechanical_failures",
                    models.CharField(
                        choices=[
                            ("OFF", "Off"),
                            ("NORMAL", "Normal"),
                            ("TIME_SCALED", "Time-scaled"),
                        ],
                        default="NORMAL",
                        help_text="LMU-specific values. Will move to Game.mechanical_failures_options for multi-sim support.",
                        max_length=15,
                    ),
                ),
                (
                    "flag_rules",
                    models.CharField(
                        choices=[
                            ("FULL", "Full"),
                            ("PARTIAL", "Partial"),
                            ("NONE", "None"),
                        ],
                        default="FULL",
                        help_text="LMU-specific values. Will move to Game.flag_rules_options for multi-sim support.",
                        max_length=10,
                    ),
                ),
                (
                    "track_limits",
                    models.CharField(
                        choices=[
                            ("STRICT", "Strict"),
                            ("NORMAL", "Normal"),
                            ("RELAXED", "Relaxed"),
                        ],
                        default="NORMAL",
                        help_text="LMU-specific values. Will move to Game.track_limits_options for multi-sim support.",
                        max_length=10,
                    ),
                ),
                ("track_limits_points", models.PositiveIntegerField(default=3)),
                ("is_dynamic", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "race",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="core.race",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RaceRulesTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "fuel_usage",
                    models.CharField(
                        choices=[
                            ("OFF", "Off"),
                            ("X1", "x1"),
                            ("X2", "x2"),
                            ("X3", "x3"),
                            ("X5", "x5"),
                        ],
                        default="X1",
                        help_text="LMU-specific values. Will move to Game.fuel_usage_options for multi-sim support.",
                        max_length=10,
                    ),
                ),
                (
                    "tire_wear",
                    models.CharField(
                        choices=[("X1", "x1"), ("X2", "x2"), ("X3", "x3")],
                        default="X1",
                        help_text="LMU-specific values. Will move to Game.tire_wear_options for multi-sim support.",
                        max_length=10,
                    ),
                ),
                ("tire_warmers", models.BooleanField(default=True)),
                (
                    "mechanical_failures",
                    models.CharField(
                        choices=[
                            ("OFF", "Off"),
                            ("NORMAL", "Normal"),
                            ("TIME_SCALED", "Time-scaled"),
                        ],
                        default="NORMAL",
                        help_text="LMU-specific values. Will move to Game.mechanical_failures_options for multi-sim support.",
                        max_length=15,
                    ),
                ),
                (
                    "flag_rules",
                    models.CharField(
                        choices=[
                            ("FULL", "Full"),
                            ("PARTIAL", "Partial"),
                            ("NONE", "None"),
                        ],
                        default="FULL",
                        help_text="LMU-specific values. Will move to Game.flag_rules_options for multi-sim support.",
                        max_length=10,
                    ),
                ),
                (
                    "track_limits",
                    models.CharField(
                        choices=[
                            ("STRICT", "Strict"),
                            ("NORMAL", "Normal"),
                            ("RELAXED", "Relaxed"),
                        ],
                        default="NORMAL",
                        help_text="LMU-specific values. Will move to Game.track_limits_options for multi-sim support.",
                        max_length=10,
                    ),
                ),
                ("track_limits_points", models.PositiveIntegerField(default=3)),
                ("is_dynamic", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_rules_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("created_by", "name"),
                        name="unique_template_name_per_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RaceWeather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "sky_condition",
                    models.CharField(
                        choices=[
                            ("CLEAR", "Clear"),
                            ("PARTLY_CLOUDY", "Partly cloudy"),
                            ("OVERCAST", "Overcast"),
                            ("LIGHT_RAIN", "Light rain"),
                            ("HEAVY_RAIN", "Heavy rain"),
                        ],
                        default="CLEAR",
                        help_text="LMU-specific values. Will move to Game.sky_condition_options for multi-sim support.",
                        max_length=15,
                    ),
                ),
                (
                    "ambient_temp",
                    models.SmallIntegerField(help_text="Ambient temperature in °C"),
                ),
                (
                    "track_temp",
                    models.SmallIntegerField(help_text="Track temperature in °C"),
                ),
                (
                    "rain_chance",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Rain probability 0-100%"
                    ),
                ),
                (
                    "rules",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_stages",
                        to="core.racerules",
                    ),
                ),
            ],
            options={
                "ordering": ["rules", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rules", "order"), name="unique_stage_order_per_rules"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("order__gte", 1), ("order__lte", 5)),
                        name="stage_order_between_1_and_5",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rain_chance__lte", 100)),
                        name="rain_chance_max_100",
                    ),
                ],
            },
        ),
    ]
