# Generated by Django 6.0.1 on 2026-01-14 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("championships", "0003_standing"),
        ("leagues", "0001_initial"),
        ("tracks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "round_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Race round number (only for championship races)",
                        null=True,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        help_text="Scheduled date and time of the race"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Race duration in minutes (e.g., 360 for 6 hours)",
                        null=True,
                    ),
                ),
                (
                    "laps",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of laps (if race is by laps instead of time)",
                        null=True,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public (Anyone can view)"),
                            ("UNLISTED", "Unlisted (Only with link)"),
                            ("PRIVATE", "Private (League members only)"),
                        ],
                        default="PUBLIC",
                        help_text="Race visibility level",
                        max_length=20,
                    ),
                ),
                (
                    "invitation_code",
                    models.CharField(
                        blank=True,
                        help_text="Invitation code for UNLISTED races",
                        max_length=32,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "entered_at",
                    models.DateTimeField(
                        blank=True, help_text="When results were entered", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the race (incidents, weather, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "championship",
                    models.ForeignKey(
                        blank=True,
                        help_text="Championship this race belongs to (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to="championships.championship",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Race creator",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_races",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who entered the results",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_races",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        blank=True,
                        help_text="League this race belongs to (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to="leagues.league",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        help_text="Track where this race takes place",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tracks.track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Race",
                "verbose_name_plural": "Races",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "total_time",
                    models.DurationField(
                        blank=True,
                        help_text="Total race time (for time-based races)",
                        null=True,
                    ),
                ),
                (
                    "laps_completed",
                    models.IntegerField(
                        blank=True, help_text="Number of laps completed", null=True
                    ),
                ),
                (
                    "fastest_lap_time",
                    models.DurationField(
                        blank=True,
                        help_text="Fastest lap time during the race",
                        null=True,
                    ),
                ),
                ("fastest_lap", models.BooleanField(default=False)),
                ("dnf", models.BooleanField(default=False, verbose_name="DNF")),
                ("dsq", models.BooleanField(default=False, verbose_name="DSQ")),
                (
                    "points",
                    models.IntegerField(
                        default=0,
                        help_text="Championship points earned (only for championship races)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes (incidents, penalties, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        help_text="Driver who achieved this result",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_results",
                        to="championships.driver",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        help_text="Race this result belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="races.race",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team this result belongs to (only for TEAM championships)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_race_results",
                        to="championships.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Race Result",
                "verbose_name_plural": "Race Results",
                "ordering": ["race", "position"],
            },
        ),
        migrations.AddConstraint(
            model_name="race",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("championship__isnull", False), ("round_number__isnull", False)
                ),
                fields=("championship", "round_number"),
                name="unique_round_per_championship",
            ),
        ),
        migrations.AddConstraint(
            model_name="raceresult",
            constraint=models.UniqueConstraint(
                fields=("race", "position"), name="unique_position_per_race"
            ),
        ),
        migrations.AddConstraint(
            model_name="raceresult",
            constraint=models.UniqueConstraint(
                fields=("race", "driver"), name="unique_driver_per_race"
            ),
        ),
        migrations.AddConstraint(
            model_name="raceresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("team__isnull", False)),
                fields=("race", "team"),
                name="unique_team_per_race",
            ),
        ),
    ]
