# Generated by Django 6.0.1 on 2026-01-13 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="League name (e.g., 'Friday Night Endurance League')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="League description and rules"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public (Anyone can join)"),
                            ("INVITE_ONLY", "Invite Only (Need invitation code)"),
                            ("PRIVATE", "Private (Admin approval required)"),
                        ],
                        default="PUBLIC",
                        help_text="League visibility and join requirements",
                        max_length=20,
                    ),
                ),
                (
                    "invitation_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique invitation code for INVITE_ONLY leagues",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="User who created this league",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_leagues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "League",
                "verbose_name_plural": "Leagues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeagueJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="Status of the join request",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional message from the user"
                    ),
                ),
                (
                    "admin_message",
                    models.TextField(
                        blank=True, help_text="Optional message from admin"
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="leagues.league",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "League Join Request",
                "verbose_name_plural": "League Join Requests",
                "ordering": ["-requested_at"],
                "unique_together": {("league", "user", "status")},
            },
        ),
        migrations.CreateModel(
            name="LeagueMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("MODERATOR", "Moderator"),
                            ("MEMBER ", "Member"),
                        ],
                        default="MEMBER ",
                        help_text="Member role in the league",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="leagues.league",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "League Membership",
                "verbose_name_plural": "League Memberships",
                "ordering": ["-joined_at"],
                "unique_together": {("league", "user")},
            },
        ),
    ]
